### ISSUE TITLE
Drag card clips

### ISSUE THREAD

**Issue by feinstein** [hongduc6/stacked_list_carousel#2] opened 2024-12-30 08:06 UTC
When I drag the card, it clips to the widget's size

![image](https://github.com/user-attachments/assets/a0ef4fea-8871-42df-b318-f22f3d3bdf75)

**Comment by curtis6636** [comment] 2024-12-30 08:52
Hi @feinstein , thank you for your feedback!

This issue was identified as a display bug caused by forgetting to set the widget's Stack clip behavior to "none," which resulted in the cards being clipped within the display boundaries. The issue has been resolved in version 1.0.2. Feel free to check it out and give it a try!

**Closed as completed by curtis6636** 2024-12-30 08:52 UTC
